# Generated by scripts/render-formula.sh from releases/lane.json. Do not edit by hand.
class Lane < Formula
  desc "Terminal Kanban board for Jira"
  homepage "https://candril.github.io/lane/"
  version "0.4.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/candril/lane/releases/download/v0.4.0/lane-darwin-arm64.gz"
      sha256 "077e2734758fe0442cbb489a092a458d28e1c2eb4f359b09338d4006bf1602ac"
    end
    on_intel do
      url "https://github.com/candril/lane/releases/download/v0.4.0/lane-darwin-x64.gz"
      sha256 "1cca0c32beb7c99bd18066c9279f739ae85fb20e2fe5132d52e0a617e1a7ea76"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/candril/lane/releases/download/v0.4.0/lane-linux-arm64.gz"
      sha256 "1486360bef2e9ccf1d120ef826aca122d59db9002748678e9ac04c39305231d2"
    end
    on_intel do
      url "https://github.com/candril/lane/releases/download/v0.4.0/lane-linux-x64.gz"
      sha256 "046c985ce3c8171841c1b1e4f5f87ea88ab17eef0ec3c11672810c58a9dff47a"
    end
  end

  def install
    bin.install Dir["lane-*"].first => "lane"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/lane --version")
  end
end
