# Generated by scripts/render-formula.sh from releases/lane.json. Do not edit by hand.
class Lane < Formula
  desc "Terminal Kanban board for Jira"
  homepage "https://candril.github.io/lane/"
  version "0.2.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/candril/lane/releases/download/v0.2.0/lane-darwin-arm64.gz"
      sha256 "83d59fdc5edead3acf29176ff70d187c99a5767467d9cb695cb362f27653cc84"
    end
    on_intel do
      url "https://github.com/candril/lane/releases/download/v0.2.0/lane-darwin-x64.gz"
      sha256 "40e76d40837f4584ab75900cc40669f8e9cec620f5a622dba3a588fc8e71f3d0"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/candril/lane/releases/download/v0.2.0/lane-linux-arm64.gz"
      sha256 "105a4e8e97bb58a91b8772593250ab3b8bf7a6e0095bcc5417e6f8ea8eb6f0bf"
    end
    on_intel do
      url "https://github.com/candril/lane/releases/download/v0.2.0/lane-linux-x64.gz"
      sha256 "cf7fd6ad7aaadf9bfa224a37255d5b881b7bd3cafcb83e0fa155cc4f65892ec6"
    end
  end

  def install
    bin.install Dir["lane-*"].first => "lane"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/lane --version")
  end
end
