# Generated by scripts/render-formula.sh from releases/monq.json. Do not edit by hand.
class Monq < Formula
  desc "Browse, query, edit. MongoDB without leaving the terminal"
  homepage "https://candril.github.io/monq/"
  version "0.7.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/candril/monq/releases/download/v0.7.0/monq-darwin-arm64.gz"
      sha256 "128f2d8373f711e9b45452fcac4a7ab7b9cee34fcd929ee32e6a64c7d46c29dc"
    end
    on_intel do
      url "https://github.com/candril/monq/releases/download/v0.7.0/monq-darwin-x64.gz"
      sha256 "9c46e14d335fe526ee2f9af1f11fdb75ec132997cae4d5e9ed0b905fec8639da"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/candril/monq/releases/download/v0.7.0/monq-linux-arm64.gz"
      sha256 "ec8d2158f4bfddbd5dc970bf55d00bbc90c025ba198a3e3775a236def37b13dc"
    end
    on_intel do
      url "https://github.com/candril/monq/releases/download/v0.7.0/monq-linux-x64.gz"
      sha256 "6ede36077f9fcd2904fb91e0cc0fea8dc4a6f3d4ff6cf9a658bca8a326eb8be6"
    end
  end

  def install
    bin.install Dir["monq-*"].first => "monq"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/monq --version")
  end
end
