# Generated by scripts/render-formula.sh from releases/monq.json. Do not edit by hand.
class Monq < Formula
  desc "Browse, query, edit. MongoDB without leaving the terminal"
  homepage "https://candril.github.io/monq/"
  version "0.8.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/candril/monq/releases/download/v0.8.0/monq-darwin-arm64.gz"
      sha256 "aeb1803b650a74137c2bfe0a171cace6cddf1117f00fedadc6ef757651fdfea5"
    end
    on_intel do
      url "https://github.com/candril/monq/releases/download/v0.8.0/monq-darwin-x64.gz"
      sha256 "988dc4ab81387f67cbde360a2e9b62a064f1c3888c796fbde38e7b30c1206635"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/candril/monq/releases/download/v0.8.0/monq-linux-arm64.gz"
      sha256 "55460f023d17e2194d7ae4cb54f621738006c98ec7d2f1961203f1cddca41a47"
    end
    on_intel do
      url "https://github.com/candril/monq/releases/download/v0.8.0/monq-linux-x64.gz"
      sha256 "8a2e66fd4879f9c9d3eb6e0e649ef14197eca1f2ba66a0b72d512390337d46cb"
    end
  end

  def install
    bin.install Dir["monq-*"].first => "monq"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/monq --version")
  end
end
