# Generated by scripts/render-formula.sh from releases/presto.json. Do not edit by hand.
class Presto < Formula
  desc "Pull requests in the terminal: every repo you watch, one list, whose move it is"
  homepage "https://candril.github.io/presto/"
  version "0.3.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/candril/presto/releases/download/v0.3.0/presto-darwin-arm64.gz"
      sha256 "ea3a2eba1e05727b09e13b198b5fe49c04fd64dd0f99f12330b5c4f1f5362b54"
    end
    on_intel do
      url "https://github.com/candril/presto/releases/download/v0.3.0/presto-darwin-x64.gz"
      sha256 "48b6bcf43073bae75736de3aa92983396d9139f06f05c2bb5a37e4785c3afc34"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/candril/presto/releases/download/v0.3.0/presto-linux-arm64.gz"
      sha256 "a25852d2c3d6e6daefc06599db9bc9f2e5c99e91b0163e3c7fe47d5c3e09877e"
    end
    on_intel do
      url "https://github.com/candril/presto/releases/download/v0.3.0/presto-linux-x64.gz"
      sha256 "9ce269d56183a382dab0f5f833aba52526e03d946c6a73ceb9b4448e958d0124"
    end
  end

  depends_on "gh"

  def install
    bin.install Dir["presto-*"].first => "presto"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/presto --version")
  end
end
