# Generated by scripts/render-formula.sh from releases/presto.json. Do not edit by hand.
class Presto < Formula
  desc "Pull requests in the terminal: every repo you watch, one list, whose move it is"
  homepage "https://candril.github.io/presto/"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/candril/presto/releases/download/v0.1.0/presto-darwin-arm64.gz"
      sha256 "a2be9acd8a17bb970f22f2c72cfa2de47ed82ca7adcca94c42dda49a7d0d5141"
    end
    on_intel do
      url "https://github.com/candril/presto/releases/download/v0.1.0/presto-darwin-x64.gz"
      sha256 "64c3ce8c71850e9317df689d73233a5223708555f3f00ec0a6d795c835f941af"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/candril/presto/releases/download/v0.1.0/presto-linux-arm64.gz"
      sha256 "b7ce5e11582686ce0c645c3ac8c10d25a779b9a3b990c2e8f2bb59f893cb634e"
    end
    on_intel do
      url "https://github.com/candril/presto/releases/download/v0.1.0/presto-linux-x64.gz"
      sha256 "41cdc90ae7c66c31f5a24b2e719530e2c1715918515ee03f9850bb305dd04e2d"
    end
  end

  depends_on "gh"

  def install
    bin.install Dir["presto-*"].first => "presto"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/presto --version")
  end
end
