# Generated by scripts/render-formula.sh from releases/riff.json. Do not edit by hand.
class Riff < Formula
  desc "Code review in the terminal: PRs, branches and working-copy diffs with vim motions"
  homepage "https://candril.github.io/riff/"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/candril/riff/releases/download/v0.1.0/riff-darwin-arm64.gz"
      sha256 "bb5b6e8425d65d786620b2629436e253725ea77f9cce0e765551c3848e012749"
    end
    on_intel do
      url "https://github.com/candril/riff/releases/download/v0.1.0/riff-darwin-x64.gz"
      sha256 "e1c4b430e25d046f7416786aa5af04d6b29629c69ad55badfd4e935727e51902"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/candril/riff/releases/download/v0.1.0/riff-linux-arm64.gz"
      sha256 "5f230bfad22ecd0137e9f868b789bd10fd56d2b1d4dd4afcfba1494b87964454"
    end
    on_intel do
      url "https://github.com/candril/riff/releases/download/v0.1.0/riff-linux-x64.gz"
      sha256 "8bc70a010c09750560d2d0a89c930d0d903861d5558d3d611975ed3467bd1690"
    end
  end

  depends_on "gh"

  def install
    bin.install Dir["riff-*"].first => "riff"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/riff --version")
  end
end
