# Generated by scripts/render-formula.sh from releases/riff.json. Do not edit by hand.
class Riff < Formula
  desc "Code review in the terminal: PRs, branches and working-copy diffs with vim motions"
  homepage "https://candril.github.io/riff/"
  version "0.3.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/candril/riff/releases/download/v0.3.0/riff-darwin-arm64.gz"
      sha256 "dafa14d045be0d1d59db42cc3e00293d7f6c60f3a08e3529f553d35f6ec4c4f8"
    end
    on_intel do
      url "https://github.com/candril/riff/releases/download/v0.3.0/riff-darwin-x64.gz"
      sha256 "1fc3a1b92382ab0cb53b0a8c512936b8f4ff206b21448c4d6e594adf1899bce4"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/candril/riff/releases/download/v0.3.0/riff-linux-arm64.gz"
      sha256 "4f59ce944a9074b365a928cbc033a79bc49470ddb1e50ca0f3a84bf81bbe2571"
    end
    on_intel do
      url "https://github.com/candril/riff/releases/download/v0.3.0/riff-linux-x64.gz"
      sha256 "92b614fd320bb238a927b86cee0487f0381bf028476f76e1ebec987e944f56f1"
    end
  end

  depends_on "gh"

  def install
    bin.install Dir["riff-*"].first => "riff"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/riff --version")
  end
end
