# Generated by scripts/render-formula.sh from releases/topiq.json. Do not edit by hand.
class Topiq < Formula
  desc "Peek, filter, replay. Kafka without leaving the terminal"
  homepage "https://candril.github.io/topiq/"
  version "0.1.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/candril/topiq/releases/download/v0.1.1/topiq-darwin-arm64.gz"
      sha256 "b2515b7a3312c5c91f7f341b75796a9b578574523b07b9bb6ed3bf2264324963"
    end
    on_intel do
      url "https://github.com/candril/topiq/releases/download/v0.1.1/topiq-darwin-x64.gz"
      sha256 "4b798c46203118e30a5711a57badcffa09fe33e0674e84ea4eea1bbeecf16375"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/candril/topiq/releases/download/v0.1.1/topiq-linux-arm64.gz"
      sha256 "547a2d3397b65081b4ecf93c23f516d32524c3afae065e09ee71d208bb5d17a8"
    end
    on_intel do
      url "https://github.com/candril/topiq/releases/download/v0.1.1/topiq-linux-x64.gz"
      sha256 "520ab8668aa38320f6264b09982b8bd9ae8ffdc1aad6bb9ea8b202b774e1c87d"
    end
  end

  def install
    bin.install Dir["topiq-*"].first => "topiq"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/topiq --version")
  end
end
