# Generated by scripts/render-formula.sh from releases/topiq.json. Do not edit by hand.
class Topiq < Formula
  desc "Peek, filter, replay. Kafka without leaving the terminal"
  homepage "https://candril.github.io/topiq/"
  version "0.4.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/candril/topiq/releases/download/v0.4.1/topiq-darwin-arm64.gz"
      sha256 "d18b2a2dd9f143ce07ef529ab29119e6a95e1209f73ffba17e931a2fcd9ce9f5"
    end
    on_intel do
      url "https://github.com/candril/topiq/releases/download/v0.4.1/topiq-darwin-x64.gz"
      sha256 "704b3d6dc9565b3f367f71e74652728078da2aab251186b57114adad000b3c07"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/candril/topiq/releases/download/v0.4.1/topiq-linux-arm64.gz"
      sha256 "f29e3186d3260ae1e7ae1e765a878a4cb970781db63673c7bb231cb27b1c9944"
    end
    on_intel do
      url "https://github.com/candril/topiq/releases/download/v0.4.1/topiq-linux-x64.gz"
      sha256 "52e1e6f898fb2e1bdd33794ce22ecf0fe29663a5059854e3caa1535fbfc12f53"
    end
  end

  def install
    bin.install Dir["topiq-*"].first => "topiq"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/topiq --version")
  end
end
