# Generated by scripts/render-formula.sh from releases/topiq.json. Do not edit by hand.
class Topiq < Formula
  desc "Peek, filter, replay. Kafka without leaving the terminal"
  homepage "https://candril.github.io/topiq/"
  version "0.3.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/candril/topiq/releases/download/v0.3.1/topiq-darwin-arm64.gz"
      sha256 "185dd2d8046b14e52db831c19c8a14cc64b7f384a28eb395db7b0ab28e549759"
    end
    on_intel do
      url "https://github.com/candril/topiq/releases/download/v0.3.1/topiq-darwin-x64.gz"
      sha256 "25ba0d3e3011f5343a3c3635ef4a6a6f4acfdd3325adfbc27cbe1b31595f0feb"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/candril/topiq/releases/download/v0.3.1/topiq-linux-arm64.gz"
      sha256 "bca671b4ea859fcd74b36a310aab0ff6e04beebb89e64e65b7057dfcbbcc75b6"
    end
    on_intel do
      url "https://github.com/candril/topiq/releases/download/v0.3.1/topiq-linux-x64.gz"
      sha256 "d5e24225a176dded8c77669fea4584c5e580bca34a2188d813d2238b0b2b331b"
    end
  end

  def install
    bin.install Dir["topiq-*"].first => "topiq"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/topiq --version")
  end
end
