#!/usr/bin/env bash
# Render Formula/<tool>.rb from tools.json and releases/<tool>.json.
set -euo pipefail
cd "$(dirname "$0")/.."

tool="$1"
rel="releases/${tool}.json"
[ -f "$rel" ] || { echo "no ${rel}: run scripts/update.sh ${tool} first" >&2; exit 1; }

class="$(tr '[:lower:]' '[:upper:]' <<<"${tool:0:1}")${tool:1}"
desc=$(jq -r ".${tool}.desc" tools.json)
homepage=$(jq -r ".${tool}.homepage" tools.json)
version=$(jq -r .version "$rel")
sum() { jq -r ".sha256[\"$1\"]" "$rel"; }
base="https://github.com/candril/${tool}/releases/download/v${version}"

deps=$(jq -r ".${tool}.brew_deps[]" tools.json | sed 's/.*/  depends_on "&"/')

{
cat <<RB
# Generated by scripts/render-formula.sh from releases/${tool}.json. Do not edit by hand.
class ${class} < Formula
  desc "${desc}"
  homepage "${homepage}"
  version "${version}"
  license "MIT"

  on_macos do
    on_arm do
      url "${base}/${tool}-darwin-arm64.gz"
      sha256 "$(sum darwin-arm64)"
    end
    on_intel do
      url "${base}/${tool}-darwin-x64.gz"
      sha256 "$(sum darwin-x64)"
    end
  end

  on_linux do
    on_arm do
      url "${base}/${tool}-linux-arm64.gz"
      sha256 "$(sum linux-arm64)"
    end
    on_intel do
      url "${base}/${tool}-linux-x64.gz"
      sha256 "$(sum linux-x64)"
    end
  end
RB
if [ -n "$deps" ]; then
  echo
  echo "$deps"
fi
cat <<RB

  def install
    bin.install Dir["${tool}-*"].first => "${tool}"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/${tool} --version")
  end
end
RB
} > "Formula/${tool}.rb"
echo "Formula/${tool}.rb ← ${tool} ${version}"
